from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import RegisterUserView, LoginView, HomeView, LogoutView, CustomTokenRefreshView, ClubUserListView, CourtViewSet

router = DefaultRouter()
router.register(r'courts', CourtViewSet, basename='court')

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('users/', ClubUserListView.as_view(), name='user-list'),
    path('', include(router.urls)),  # Include all routes generated by the router

]
